version: '3.3'

services:
  db-node-1:
    build:
      context: mariadb
      dockerfile: db-node-01/Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    # command: >
    #   --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    #   --general-log=ON
    #   --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: mariadb
      dockerfile: db-node-02/Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    networks:
      - arch-network
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql

  proxysql:
    image: proxysql/proxysql:2.0.6
    command: >
      --initial
    volumes:
    - "./proxysql/proxysql.cnf:/etc/proxysql.cnf"
    - proxysql-data:/var/lib/proxysql
#    healthcheck:
#      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
#      timeout: 20s
#      retries: 5
    networks:
      - arch-network
    ports:
    - "6033:6033"
    - "6032:6032"
    depends_on:
      - db-node-1
      - db-node-2

  fastapi_backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: unless-stopped
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_USER=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - CACHE_HOST=cache
      - CACHE_POST=6379
      - CACHE_EXPIRATION=60
    ports:
      - "8000:8000"
    networks:
      - arch-network
    depends_on:
      - proxysql
      - cache
      - db-node-1
      - db-node-2
#        condition: service_healthy

  streamlit_app_frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: streamlit_app_frontend
    restart: unless-stopped
    environment:
      - MARKET_SERVICE_HOST=fastapi_backend
      - MARKET_SERVICE_PORT=8000
    ports:
      - "8501:8501"
    depends_on:
      - fastapi_backend
    networks:
      - arch-network

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - arch-network
    volumes:
      - cache:/data

volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data:
  cache:

networks:
  arch-network:
    driver: "bridge"
    external: false